version: "3.4"

services:

    nginx_metavolcano:
        build: ./build/nginx
        container_name: metavolcano_webserver
        ports:
            - "8090:80"
        volumes:
            - ./volumes/metavolcano-front:/var/volumes/metavolcano-front
        depends_on:
             - php_metavolcano
        networks:
            - webserver
            - php
        restart: always

    php_metavolcano:
        build: ./build/php
        container_name: metavolcano_php
        volumes:
            - ./.git/modules/volumes/metavolcano-front:/var/.git/modules/volumes/metavolcano-front
            - ./volumes/metavolcano-front:/var/volumes/metavolcano-front
        networks:
             - php
        environment:
             - REPOSITORY=${REPOSITORY}
             - BRANCH_STABLE=${BRANCH_STABLE}
             - TOKEN=${TOKEN}
        restart: always
        command: /bin/bash -c "envsubst '$${REPOSITORY} $${BRANCH_STABLE} $${TOKEN}' < /tmp/deploy-config.php > /var/volumes/metavolcano-front/hook/deploy-config.php && php-fpm"

networks:
    webserver:
    php:
